name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync resume-site s3://wilkin-cloud-resume --delete

      # Add CloudFront cache invalidation step here if needed
